### ISSUE TITLE
Problem Overriding REDSHIFT_CMB

### ISSUE THREAD

**Issue by nfshermy** [RickKessler/SNANA#1455]
Hello!
I am using SNANA for LC fitting, and it's been working as expected so far, but all of a sudden it no longer seems to be reading the header override file correctly anymore, and data with known z is being fitted to the wrong z (much much different). 

Here is a a snippet of my override file
```
DOCUMENTATION:
  PURPOSE: Inject peakmjds into the data
  REF:
  - AUTHOR: Nora Sherman
  - DATE: 02.12.23
DOCUMENTATION_END:
VARNAMES: CID IAUC RA DEC PKMJD REDSHIFT_CMB REDSHIFT_CMB_ERR VPEC HOSTGAL_LOGMASS HOSTGAL_RA HOSTGAL_DEC
SN: 1378707 2021acxb 49.9027958 -27.4940333 59528 0.06365 0.00001 -10.54 11.19054828 49.9049134 -27.4965505
SN: 1370113 2021aefx 64.9721667 -54.9479444 59550 0.00473963 0.0005 -312.27 10.39459102 65.00165353 -54.93795131
```
But, after running fitting, for CID 1378707, I get a zHEL of 1.17004. Given the override REDSHIFT_CMB value of 0.06365, this seems hugely excessive! There are several examples of this as well.

The most concerning part, however, is that not long ago I was getting very normal zHEL values, but I just updated my override file, and then this started happening, so I hazard that it might be an issue with my override file, but I cannot identify what might be going wrong (it looks identical but for the updated values in the file which, I am convinced, should not result in such high zHELs). 

Any assistance is greatly appreciated. Thank you!
