### ISSUE TITLE
Create separate mappings for CfA3 instruments

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#325]
Currently, in the SALT2 training with submit_batch_jobs, CfA3 maps to Standard, Keplercam, and 4Shooter2 instrument files, so all three are perturbed with a call to CfA3.  It'd be good to be able to perturb each instrument individually. I think that all we need to do is add some entries to survey.yaml to specify different instruments, i.e. by adding the following:

```
CfA3_4SHOOTER2:
    MagSys: VEGA2
    MagSys_filename: BD17-jla1.dat
    Instrument: [ 4SHOOTER2 ]
    Instrument_subdir: [ 4Shooter2 ]
    Bands: [ Us, B, V, R, I ]
    SNANA_INSTR:  [ CFA3S ]
    SNANA_BANDS:  [ s, B, V, R, I ] ??q

CfA3_STANDARD:
    MagSys: VEGA2
    MagSys_filename: BD17-jla1.dat
    Instrument: [ STANDARD]
    Instrument_subdir: [ SNLS3-Landolt-model ]
    Bands: [ U, B, V, R, I ]
    SNANA_INSTR:  [ CFA3 ]
    SNANA_BANDS:  [ U, B, V, R, I ]

CfA3_KEPLERCAM:
    MagSys: VEGA2
    MagSys_filename: BD17-jla1.dat
    Instrument: [ KEPLERCAM ]
    Instrument_subdir: [ Keplercam ]
    Bands: [ Us, B, V, r, I ]
    SNANA_INSTR:  [ CFA3K ]
    SNANA_BANDS:  [ s, B, V, r, i ]
```

I can do this, but I need a few things confirmed:
- The SURVEY_MAP_FILE for submit_batch_jobs currently points to the survey.yaml file in the T20 SALTPATH in my user directory. Are we happy with keeping it there, or could we point it to the copy in $PRODUCTS/snpca instead?
- Do we want to keep a 'CfA3' option that perturbs all three instruments? If so, there should maybe be a warning message that a call to this survey will perturb multiple instruments at once.
- Are the SNANA_INSTR and BANDS I've included above correct, and are you happy with the CfA3_INSTRUMENT formatting, or is there something else that makes more sense?
- I noticed that SNANA_INSTR and SNANA_BANDS sections are missing for Calan/Tololo and Other, is that intentional/fine?

Once I get the go-ahead on this, I'll update survey.yaml and do some tests.
